name: CI-CD Terraform Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  package-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # â¿¡ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # â¿¢ Check folder structure (debugging step - optional but useful)
      - name: List repo files
        run: |
          pwd
          ls -R event-driven-pipeline

      # â¿£ Set up Python for Lambda packaging
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # â¿¤ Build Lambda zip files
      - name: Build Lambda functions
        run: |
          chmod +x event-driven-pipeline/scripts/lambda.sh
          ./event-driven-pipeline/scripts/lambda.sh

      # â¿¥ Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ AKIARJHKLYNZB32NXQXV }}
          aws-secret-access-key: ${{ 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 }}
          aws-region: ${{ secrets.AWS_REGION }}

      # â¿¦ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      # â¿§ Terraform Init
      - name: Terraform Init
        working-directory: event-driven-pipeline/terraform
        run: terraform init

      # â¿¨ Terraform Validate
      - name: Terraform Validate
        working-directory: event-driven-pipeline/terraform
        run: terraform validate

      # â¿© Terraform Plan
      - name: Terraform Plan
        working-directory: event-driven-pipeline/terraform
        run: |
          terraform plan \
            -var="processor_zip_path=my_lambdas/processor.zip" \
            -var="report_zip_path=my_lambdas/report.zip" \
            -var="raw_bucket_name=archana-devops-raw-2025" \
            -var="processed_bucket_name=archana-devops-processed-2025"

      # ðŸ”Ÿ Terraform Apply
      - name: Terraform Apply
        working-directory: event-driven-pipeline/terraform
        run: |
          terraform apply -auto-approve \
            -var="processor_zip_path=my_lambdas/processor.zip" \
            -var="report_zip_path=my_lambdas/report.zip" \
            -var="raw_bucket_name=archana-devops-raw-2025" \
            -var="processed_bucket_name=archana-devops-processed-2025"
