name: CI-CD Terraform Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  package-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ğŸ§© Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # ğŸ“‚ Check folder structure (debugging step)
      - name: List repo files
        run: |
          pwd
          ls -R event-driven-pipeline

      # ğŸ Set up Python for Lambda packaging
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # ğŸ“¦ Build Lambda zip files
      - name: Build Lambda functions
        run: |
          chmod +x event-driven-pipeline/scripts/lambda.sh
          ./event-driven-pipeline/scripts/lambda.sh

      # ğŸ” Configure AWS credentials (from GitHub Secrets)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: AKIARJHKLYNZHY5YOLPZ
          aws-secret-access-key: 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
          aws-region: us-east-1

      # âš™ï¸ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      # ğŸ§± Terraform Init
      - name: Terraform Init
        working-directory: event-driven-pipeline/terraform
        run: terraform init

      # âœ… Terraform Validate
      - name: Terraform Validate
        working-directory: event-driven-pipeline/terraform
        run: terraform validate

      # ğŸ“‹ Terraform Plan
      - name: Terraform Plan
        working-directory: event-driven-pipeline/terraform
        run: |
          terraform plan \
            -var="processor_zip_path=my_lambdas/processor.zip" \
            -var="report_zip_path=my_lambdas/report.zip" \
            -var="raw_bucket_name=archana-devops-raw-2025" \
            -var="processed_bucket_name=archana-devops-processed-2025"

      # ğŸš€ Terraform Apply
      - name: Terraform Apply
        working-directory: event-driven-pipeline/terraform
        run: |
          terraform apply -auto-approve \
            -var="processor_zip_path=my_lambdas/processor.zip" \
            -var="report_zip_path=my_lambdas/report.zip" \
            -var="raw_bucket_name=archana-devops-raw-2025" \
            -var="processed_bucket_name=archana-devops-processed-2025"
